### ISSUE TITLE
Link overlay not filling the div

### ISSUE THREAD

**Issue by bennettscience** [cogdog/truwriter#1]
On a full-width (1440 x 900) screen, the title overlay isn't completely covering the header image.

![2015-01-02_11-09-35](https://cloud.githubusercontent.com/assets/3878010/5597419/f55aed66-926f-11e4-8e00-c4b33ecc83b4.png)

It's an easy fix: add `height:100%` to the `a.post-header` class. It'll cover the header, regardless of size.

This brings up a separate issue, though - your content isn't in any kind of wrapper div to keep it centered. I'd suggest creating a `title-wrap` class and positioning it using the following:
```
position:relative;
top:50%;
transform:translateY(-50%);
```

That will vertically center the content without playing around with margins or padding too much.

**Comment by cogdog** [comment]
Thanks a lot Brian, the 100% height on the overlay works better. The I had
added some CSS to make the background image sizes more regular height (a
max-height), so the overlay was a bit off.

So it's not properly centring on the big screen? I'll look into that, where
would that title-wrap div go?

thanks

On Fri, Jan 2, 2015 at 8:10 AM, Brian <notifications@github.com> wrote:

> On a full-width (1440 x 900) screen, the title overlay isn't completely
> covering the header image.
>
> [image: 2015-01-02_11-09-35]
> <https://cloud.githubusercontent.com/assets/3878010/5597419/f55aed66-926f-11e4-8e00-c4b33ecc83b4.png>
>
> It's an easy fix: add height:100% to the a.post-header class. It'll cover
> the header, regardless of size.
>
> This brings up a separate issue, though - your content isn't in any kind
> of wrapper div to keep it centered. I'd suggest creating a title-wrap
> class and positioning it using the following:
>
> top:50%;
> transform:translateY(-50%);
>
> That will vertically center the content without playing around with
> margins or padding too much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cogdog/truwriter/issues/1>.
>



-- 


*--------------------------------------------------------------------Alan
Levine: A Cog, A Dog, A Blog*
cogdogblog.com • cogdog.info
StoryBox • cogdogblog.com/storybox


photoing on flickr <http://flickr.com/photos/cogdog> & Barking Dog Studios
<http://barkingdog.me> • tweeting @cogdog <http://twitter.com/cogdog>
50+ Web 2.0 Ways to Tell a Story -- 50ways.wikispaces.com
--------------------------------------------------------------------

**Comment by bennettscience** [comment]
Put it just inside the anchor tag with the `post-header` class and end it after `theauthor` (paragraph tag). It'll wrap the information and center it vertically in the box. You don't need to change any padding or anything. It's the method I used to [center title information](http://dev.brianbennett.org/anchor/) when I made a theme for Anchor CMS.

**Comment by cogdog** [comment]
I'll need to tinker with this. There are some funky things that happened I
think  because of the way the thumbnails behind the text are sized by
backstretch.js I can live for now w/o perfect height centered text

On Sat, Jan 3, 2015 at 3:45 AM, Brian <notifications@github.com> wrote:

> Put it just inside the anchor tag with the post-header class and end it
> after theauthor (paragraph tag). It'll wrap the information and center it
> vertically in the box. You don't need to change any padding or anything.
> It's the method I used to center title information
> <http://dev.brianbennett.org/anchor/> when I made a theme for Anchor CMS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cogdog/truwriter/issues/1#issuecomment-68592327>.
>



-- 


*--------------------------------------------------------------------Alan
Levine: A Cog, A Dog, A Blog*
cogdogblog.com • cogdog.info
StoryBox • cogdogblog.com/storybox


photoing on flickr <http://flickr.com/photos/cogdog> & Barking Dog Studios
<http://barkingdog.me> • tweeting @cogdog <http://twitter.com/cogdog>
50+ Web 2.0 Ways to Tell a Story -- 50ways.wikispaces.com
--------------------------------------------------------------------

**Comment by cogdog** [comment]
This was still causing display problems (first post was positioned wrong when there was just 1, and weird overlays for different sized titles) and I got tired of banging my head on CSS. 

I removed all my custom CSS that was doing this to try and make the featured images the same size, and reverted it to the way the theme designer does it (he knows more than me). It does mean that tall images will be bigger on the index, but it's more uniform now.... see it at http://splot.ca/writer
