### ISSUE TITLE
re-edit links not sending

### ISSUE THREAD

**Issue by jrdingwall** [cogdog/truwriter#14]
Installed the latest versions of Radcliffe and TRU Writer. When someone submits to the website and provides their email, the re-edit link is not automatically being sent to the author. Returning to the page and clicking the "request now" button for the link also does nothing. 

The site admin can see the email and the custom link in the meta data fields, just the auto email feature does not appear to be working. Checked email spam folders as well.

**Comment by cogdog** [comment]
Email sending can be tricky to debug. It's working on my test site at http://splot.ca/writer (those words never comfort).

Stuff to check:

- Do you have TRU Writer options to email notify admins on new submissions? Are those coming through? They are sent in a similar way

- Edit a post, turn on Custom fields; is there an email address in the one for wEmail?

- When clicking the "Request Now" button does a confirmation box appear with "Email instructions sent to author"?

- Might need to poke around error logs for email.

It's not anything I can easily debug. Worst case is having to email authors the edit link in the dashboard. I'll try to think of other possible hangups, sorry.

**Comment by jrdingwall** [comment]
Thanks Alan! The troubleshooting checks you provided helped me to track down the issue. Turned out to be a user error in the page set-up (get-edit-link had been altered). All is good. Thanks again.
