### ISSUE TITLE
Delegating post/comment approval via roles

### ISSUE THREAD

**Issue by francesbell** [cogdog/truwriter#15]
Using Truwriter at femedtech.net, we approve posts and comments usind admin account. Is it possible to use a role (say Editor) that can approve posts /comments but not have broader permission eg structural change?

**Comment by cogdog** [comment]
Sure; but role capabilities are not done in the theme. You can try a plugin that lets you customize the roles and capabilities of the Editor role as described. 

Try Capability Manager Enhanced

https://wordpress.org/plugins/capability-manager-enhanced/

or User Role Editor

https://wordpress.org/plugins/user-role-editor/

**Comment by francesbell** [comment]
Thanks Alan.
I will share this with femedtech, and see if we can get a small team to work on this. It would be good to do a bit of work to enable delegation of some aspects of the admin for particular activities. It should help with sustainability of femedtech via femedtech.net.
