### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by noahrmitchell** [cogdog/truwriter#17]
Heya- slight problem with responsiveness on a page title on this site: 
https://wall-it.eduhack.eu/category/published/area1/activity-1-1/

Setting .page-title section.light-padding to width: 100% seemed to resolve it. Does that make any sense? (New to coding). 

Thanks! Noah (Cov Uni DMLL)

**Comment by cogdog** [comment]
Great catch! It's a missing style in the parent Radcliffe theme. You can put css below in Custom CSS until it gets updated

I will be updating theme using a slightly different selector (affects archive pages that use page-title class)

```
/* fix to keep archive titles responsive h/t noah mitchell */
.archive .page-title {
    width: 100%;
}
```

**Comment by noahrmitchell** [comment]
Thanks!

I looked for custom css in appearance > customiser but didn’t see that
option. I couldn’t find anything in style.css or I would I attempted a pull
request (then I remembered it was a child theme!)

I’ve just been roped in by some project partners to take a look at their
site.

Will the code you provided be added to the style.css file or is there a
sheet somewhere else? Just curious.

Cheers,

Noah

**Comment by cogdog** [comment]
Right. In multisite you need to have a network administrator role to see the Additional CSS panel in the Customizer (I can see that on your site, I have just a site admin account, and I cannot access it).

There's no other way to modify CSS, that's a weird factor or multisite, as a site admin you are more like Admin Junior

I will push a change right now to the TRU Writer theme. You can let Daniel know or tell him just to copy the style.css from github.

**Comment by noahrmitchell** [comment]
Thanks, that’s helpful!

If I see anything else, I’ll have a go at the whole pull request thing.

(Lauren’s successfully done one with some theme developer’s code by adding
some missing spaces, and I’m keen to catch up).

Thanks for all you do!

**Comment by cogdog** [comment]
No need to pull. I already submitted the change and the updated stylesheet is available at

https://github.com/cogdog/truwriter/blob/master/style.css

(note the credit line ;-)
