### ISSUE TITLE
Header Images

### ISSUE THREAD

**Issue by mpelzel** [cogdog/truwriter#18]
Hi Alan, we're putting the TRU Writer splot to use[ here](http://resilience.sites.grinnell.edu/), and had a quick question. Is there a way to toggle off the header image block in the writing editor? I'm not sure we want every entry to require a person to submit a header image, or that we want the site to have that look. I know the images can be removed before publishing the posts, but just wanted to check what other options might be. Thanks, all best, and be well...Mo

**Comment by cogdog** [comment]
That looks like a great start, Mo!

I had that question before and have been thinking I should add an option to make the header images optional. It ends up grey otherwise on the index listings. I could add a Customizer option to choose a background color.

It's not too much to fold this in, will try to poke around over the weekend.

And be well too! I'm worried about y'all.

**Comment by mpelzel** [comment]
Thanks Alan! It's not a huge deal, so no need to take up a lot of your weekend time. We could also throw some language up there to explain to contributors what a header image is in this context and/or give them some default image options to use if they aren't sure of what to use.

Thanks for the good wishes!

**Comment by cogdog** [comment]
Twas fun to do, updated the theme here with some new options you can use to disable image uploads, or make them optional.

See it in use at https://splot.ca/writer in this example https://splot.ca/writer/2020/771

It's lightly tested, so let me know if it works.

**Comment by cogdog** [comment]
Never need to re-install. Best way is to download the latest version of the theme from this repo https://github.com/cogdog/truwriter

I prefer ftp/sftp so you can transfer all the files, but you can do it via the file manager by uploading a zip to the wp-content/themes directory, then expanding it.

One note, the download from here has a different directly name; it shows up as `truwriter-master` so when you download it to your computer, expand it locally, rename the directory to be just  `truwriter` and rezip. That's the one to upload.

Or if that's messy, you can use this plugin https://wordpress.org/plugins/easy-theme-and-plugin-upgrades/ to upload a new version of an existing theme in the WordPress interface (you still need to do the changing of the zip name, sorry)

**Comment by mpelzel** [comment]
Got it. Thanks, looking good so far https://resilience.sites.grinnell.edu.

**Comment by cogdog** [comment]
Looks good!

Yes I realized that discrepancy too. I might make the change you suggested. If I was fancier I would get some jQuery going to hide the caption field if no image was uploaded.

Also, you might look into the Customizer as you modify the titles and instructions or all the form field elements; see https://github.com/cogdog/truwriter#customize-the-writing-form-prompts

**Comment by mpelzel** [comment]
Yup, did that in the Customizer. So subhead now reads "Provide full credit / attribution ... required only if using a header image." But the editor won't allow me to remove the word "required" in the main head of the prompt. Oh well, no problem ... people should be able to figure it out.

**Comment by cogdog** [comment]
That part was hardwired in the theme. I added some more logical to handle this. Replace page-write.php in your theme with this newer version

https://github.com/cogdog/truwriter/blob/master/page-write.php

**Comment by mpelzel** [comment]
Got it ... thank you!!
