### ISSUE TITLE
Categories not appearing in writing form after updating

### ISSUE THREAD

**Issue by erika-b** [cogdog/truwriter#23]
Hi Alan!

After updating TRUWriter, I noticed that my categories are no longer showing up on the writing prompt, both for users or as a drop down in the TRUWriter Options dashboard: 
![image](https://user-images.githubusercontent.com/37821035/205736504-854e061f-0854-433b-9cb4-9050a397f51a.png)
![image](https://user-images.githubusercontent.com/37821035/205736663-e3fb47be-8e67-4402-835d-8c20976bcd6d.png)
(under the TRUWriter options, that drop down is empty despite having several categories)
 
However, when I go to Writing Categories they are still there, and I am able to set a default category via "Settings > Writing" 
![image](https://user-images.githubusercontent.com/37821035/205737055-ebcb5ac8-a650-4c38-875f-f0823f231138.png)

Any suggestions? Thank you!

**Comment by cogdog** [comment]
Hi there, sorry for the loss of categories. A few questions:

**(1) Can you verify the version of TRU Writer in use?** 
Under Appearance, Themes, click on Theme Details. The most current version is 3.3, what is yours?

**(2) The default category setting under Settings -> Writings has no effect on TRU Writer.**

**(3) Double Check the Settings under TRU Writer Options**

For "Use categories as options for submission or only for admin use" select "Yes, options on share form and display on single item" (I think that is what you have set).

**(4) Check the Category Structure**

TRU Writer looks for categories to provide to both the options and the users as ones that are all child categories of a main category called "Published" -- if there is not top level category created for "Published" then it will see an empty list (this was done to allow categories outside of ones users see). Make sure you have a top level category called **Published**

This is the set up for the demo site at https://splot.ca/writer


![Screen Shot 128](https://user-images.githubusercontent.com/463038/205754431-023af00c-1531-4dac-940b-b9ae9ce9c865.jpg)

You can edit any categories to move them under there by setting their Parent to one called Published.

**Comment by erika-b** [comment]
Thanks for the quick reply, Alan! It looks like the issue was #4, the category structure. I am curious--do you think the categories hierarchies were deleted/flattened when I updated? I noticed this happened to all the splots I support (this could also be something I overlooked and am just catching now too!).

**Comment by cogdog** [comment]
Can you tell me if this is happening after a WordPress version update or updating the theme? I have never seen a category hierarchy changed by either. But I cannot discount what you observed. 

I am checking a few other sites to see if I can find an occurence.
