### ISSUE TITLE
Bug: Unparenthesized

### ISSUE THREAD

**Issue by HananoshikaYomaru** [cogdog/truwriter#24]
The `/write` page cannot be opened. Whenever it is opened, an error will be thrown. 

there is a bug on `page-write.php`

```
 Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ?
 d : e)` in /var/www/webroot/ROOT/wp-content/themes/truwriter-master/page-write.php on line 26
```

**Comment by HananoshikaYomaru** [comment]
a minor syntax issue. fixed it.

**Comment by cogdog** [comment]
Thanks for noting this. I believe you might not be using the [current version of this template of this theme](https://github.com/cogdog/truwriter/blob/master/page-write.php), this was changed to address this error. The current version is 3.32 -- [details on updating in the docs](https://github.com/cogdog/truwriter/blob/master/docs.md#updating-the-tru-writer-theme)

See, where (now on line 27) it reads

`$wAccessCodeOk = ((isset( $_POST['wAccessCodeOk'] )) ? true : (is_customize_preview())) ? true : false;`

Does that match your correction? 

I'm glad the theme is getting some use, I have not done much more to it recently, but as far as I know its functional. If possible, I always enjoy seeing sites using it.
