### ISSUE TITLE
Add Media button not visible on writing form

### ISSUE THREAD

**Issue by erika-b** [cogdog/truwriter#25]
Has anyone else had an issue with the "Add Media" button on the writing form? It is visible on the "TRU Writer Options" page 
![image](https://github.com/user-attachments/assets/510a5d14-6e58-40bd-9a62-d7f882f4fba4)

but then on the front-end it isn't visible 
![image](https://github.com/user-attachments/assets/d1c2a8ce-52c1-4278-a294-e35f7f9a6591)
 
I've re-installed both Radcliffe and TRU Writer (including adding WP Pusher). This isn't an issue on other TRU Writer SPLOTs on this domain. I feel like it must be a WP setting I am missing!

**Comment by cogdog** [comment]
With TRU Writer will not see the Add Media button on the front end form, the one you are seeing in the SPLOT options is the default WordPress editor when you are logged into your site.

What you should see ([as on the demo site](https://splot.ca/writer/write)) is the icon on the far right to add an image

![Screenshot 243](https://github.com/user-attachments/assets/db4acf07-b883-439d-ad5a-000c44603aa9)

It would help to know what version of the theme you are running or a link to the site so I can inspect. I am suspecting you do not have a current version of TRU Writer. Did you use WP Pusher to connect to the source? Did you ask it to update?

Do you by chance have two different versions of the theme installed?

**Comment by erika-b** [comment]
I used WP Pusher to connect to the source and updated it today. There were two versions of the theme installed but I've deleted the old one and it didn't fix the problem. Here is the site: https://rikithompson.ds.lib.uw.edu/visuallife/

Thank you for your help!

**Comment by erika-b** [comment]
Ah, I am not sure how this happened, but there were multiple "write" forms/pages! Now that I've deleted them and reverted back to the original "/write" the media button is there. 

Thanks for your help/quick responses!

**Comment by cogdog** [comment]
Yes, the multiple themes can happen when you set up WP Pusher, it has to do with the way the GitHub downloads are named. Glad that it solved the problem.

The extra write pages can happen when the theme thinks its new, you did well to clean up.

And wow, am I super excited to see how you are teaching comics and the work your students are doing. And if by any chance you know or work with Chris Lott there at UW-Tacoma, tell him hello and I owe an overdue email. He is a long time friend.

**Comment by erika-b** [comment]
Thank you!! That is really helpful. 

I'm in the library supporting this class, taught by Dr. Riki Thompson (I think some students in her other class may have mistakenly posted in your demo site last term, apologies for that!). I'll make sure to give Chris a hello from you!

Thanks again, Alan!
